she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('all-reviews', views.ALLIndexView.as_view(), name='index-all'),
    path('<int:pk>/', views.StoryView.as_view(),name='story'),
    path('add-story/', views.AddStoryView.as_view(), name = 'newsStory'),
    path('edit/<int:pk>/', views.EditStoryView.as_view(),name='editStory'),
    path('delete/<int:pk>/', views.DeleteStoryView.as_view(),name='deleteStory'),
    path('one_author/<str:username>/', views.OneAuthorView.as_view(), name = 'one_author'),
    path('filter/', views.CategoryFilterView.as_view(), name = 'filtering-cat'),
    path('like/<int:pk>/', views.LikeView, name = 'like-post'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include
#told it about apps urls
#' this tells you where the news app is located
urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/',include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    path('create-account/', views.CreateAccountView.as_view(), name ='createAccount'),
    path('profile/<str:username>/', views.UserProfileView.as_view(), name ='profile'),
    path('profile/<str:username>/edit/', views.EditAccountView.as_view(),name='editAccount'),
]

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here
Cuisine_CHOICES = [
    ('French', 'French'),
    ('Italian', 'Italian'),
    ('Modern Australian', 'Modern Australian'),
    ('Indonesian', 'Indonesian'),
    ('Chinese', 'Chinese'),
    ('Japanese', 'Japanese'),
    ('Thai', 'Thai'),
    ('American', 'American'),
    ('Middle Eastern', 'Middle Eastern'),
    ('Indian', 'Indian'),
    ('Moroccan', 'Moroccan'),
    ('Other', 'Other'),
]
class CustomUser(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    Cuisine_CHOICES = [
        ('French', 'French'),
        ('Italian', 'Italian'),
        ('Modern Australian', 'Modern Australian'),
        ('Indonesian', 'Indonesian'),
        ('Chinese', 'Chinese'),
        ('Japanese', 'Japanese'),
        ('Thai', 'Thai'),
        ('American', 'American'),
        ('Middle Eastern', 'Middle Eastern'),
        ('Indian', 'Indian'),
        ('Moroccan', 'Moroccan'),
        ('Other', 'Other'),
    ]
    favourite_cuisine = models.CharField(
        max_length=20,
        choices=Cuisine_CHOICES,
        default='Other',
    )

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm,ReadOnlyPasswordHashField
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username','email','bio','location','favourite_cuisine']
    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
        return user



class CustomUserChangeForm(UserChangeForm):
    password = ReadOnlyPasswordHashField(label="",
        help_text=("")
    )

    class Meta:
        model = CustomUser
        fields = ['username','email','bio','location','favourite_cuisine']



  

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm,CustomUserChangeForm
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import User

User = CustomUser

# Create your views here.

class CreateAccountView(generic.edit.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserProfileView(generic.TemplateView):
    template_name = 'users/profile.html'


class EditAccountView(generic.edit.UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    template_name = 'users/editAccount.html'
    def get_success_url(self):
        return reverse_lazy('users:profile', kwargs={"username": self.request.user.username})
    slug_field = 'username'
    slug_url_kwarg = 'username'

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
<h2>Create Account</h2>
<div id = "form-container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="submitbutton"  type="submit">Create Account</button>
    </form>
</div>
<div class="container-linking"> 
    <p id = "connect-page-p">Already have an account?  Log in <a id="linkcolour" href="{% url 'login' %}">here!</a> </p>
</div>
{% endblock %}

she_codes_news/users/templates/users/editAccount.html
{% extends 'base.html' %}

{% block content %}
<h2>Edit Account Details</h2>

<div id = "changepass">
    <a class="editaccount" href="{% url 'password_change' %}">Change password here</a>
    </div>
    

<div id = "form-container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="submitbutton"  type="submit">Update Account Details</button>
    </form>
</div>


{% endblock %}

she_codes_news/users/templates/users/profile.html
{% extends 'base.html' %}


{% block content %}
{% if user.is_authenticated %}


    <h2>Hi {{request.user}}! </h2>
    <h2>Your Profile Details </h2>
    <p>Location: {{request.user.location}}</p>
    <p>Favourite Cuisine: {{request.user.favourite_cuisine}}</p>
    <p>A bit about {{request.user}}: {{request.user.bio}}</p>

    <a class = "editaccount" href="{% url 'users:editAccount' request.user%}">Change & Update Account Details</a >

{% endif %}

{% endblock %}