she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('all-reviews', views.ALLIndexView.as_view(), name='index-all'),
    path('<int:pk>/', views.StoryView.as_view(),name='story'),
    path('add-story/', views.AddStoryView.as_view(), name = 'newsStory'),
    path('edit/<int:pk>/', views.EditStoryView.as_view(),name='editStory'),
    path('delete/<int:pk>/', views.DeleteStoryView.as_view(),name='deleteStory'),
    path('one_author/<str:username>/', views.OneAuthorView.as_view(), name = 'one_author'),
    path('filter/', views.CategoryFilterView.as_view(), name = 'filtering-cat'),
    path('like/<int:pk>/', views.LikeView, name = 'like-post'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include
#told it about apps urls
#' this tells you where the news app is located
urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/',include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    path('create-account/', views.CreateAccountView.as_view(), name ='createAccount'),
    path('profile/<str:username>/', views.UserProfileView.as_view(), name ='profile'),
    path('profile/<str:username>/edit/', views.EditAccountView.as_view(),name='editAccount'),
]

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes Eats</title>
        <meta name="description" content="">
        <meta name="author" content="Ellen Marinko">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>

            <div id = 'header-container'>
                <div id="header-text">
                    <a id="header-link" href="{% url 'news:index' %}">
                        <h1>She {Codes} Eats</h1>
                    </a>
                </div>

                    <div id="cuisine-types">
                        <a class = "navbar" href="{% url 'news:index-all' %}">All </a>
                        {% for x,y in categories %}
                            <a class = "navbar" href="{% url 'news:filtering-cat' %}?cuisine_type={{x}}"> {{x}} </a>
                        {% endfor %}
                    </div>  
                </div>
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        <!-- put template data in block -->
        {% block content %} {% endblock %}
    </body>

    <footer>
        <p>Ellen Marinko © 2020 </p>
        <p>Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a></p>
    </footer>

</html>

she_codes_news/templates/nav.html
<nav>
    <a class = "navbar" href="{% url 'news:index' %}"></a>

    <a class = "navbar" href="{% url 'news:index' %}">Home</a>

    {% if user.is_authenticated %}
        <a class = "navbar" id = "loggedinuser" href="{% url 'users:profile' user.username%}">{{user.username}}</a>
        <a class = "navbar" href="{% url 'logout' %}">Logout</a>
        <a class = "navbar" id='empreview' href="{% url 'news:newsStory' %}">Write a review</a>

    {% else %}
        <a class = "navbar" href="{% url 'login' %}">Login</a>
        <a class = "navbar"  href="{% url 'users:createAccount' %}">Create an account</a>
    {% endif %}


</nav>