she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('all-reviews', views.ALLIndexView.as_view(), name='index-all'),
    path('<int:pk>/', views.StoryView.as_view(),name='story'),
    path('add-story/', views.AddStoryView.as_view(), name = 'newsStory'),
    path('edit/<int:pk>/', views.EditStoryView.as_view(),name='editStory'),
    path('delete/<int:pk>/', views.DeleteStoryView.as_view(),name='deleteStory'),
    path('one_author/<str:username>/', views.OneAuthorView.as_view(), name = 'one_author'),
    path('filter/', views.CategoryFilterView.as_view(), name = 'filtering-cat'),
    path('like/<int:pk>/', views.LikeView, name = 'like-post'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include
#told it about apps urls
#' this tells you where the news app is located
urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/',include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    path('create-account/', views.CreateAccountView.as_view(), name ='createAccount'),
    path('profile/<str:username>/', views.UserProfileView.as_view(), name ='profile'),
    path('profile/<str:username>/edit/', views.EditAccountView.as_view(),name='editAccount'),
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models
from users.models import CustomUser, Cuisine_CHOICES




class NewsStory(models.Model):
    Cuisine_CHOICES = [
        ('French', 'French'),
        ('Italian', 'Italian'),
        ('Modern Australian', 'Modern Australian'),
        ('Indonesian', 'Indonesian'),
        ('Chinese', 'Chinese'),
        ('Japanese', 'Japanese'),
        ('Thai', 'Thai'),
        ('American', 'American'),
        ('Middle Eastern', 'Middle Eastern'),
        ('Indian', 'Indian'),
        ('Moroccan', 'Moroccan'),
        ('Other', 'Other'),
    ]
    cuisine_type = models.CharField(
        max_length=30,
        choices=Cuisine_CHOICES,
        default='Other',
    )
    
    CHOICES = [('1','Awful'),('2','Average'),('3','Okay'),('4','Good'),('5','Fantastic')]
    Food_rating = models.CharField(
        max_length=20,
        choices=CHOICES,
        default=3,
    )

    title = models.CharField(max_length=200)
    Restaurant = models.CharField(max_length=200)

    author = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name="stories"
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image_upload = models.URLField(default="",max_length=500)
    likes = models.ManyToManyField(CustomUser, related_name = "story")

    def total_likes(self):
        return self.likes.count()

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm, SplitDateTimeField, SplitDateTimeWidget
from .models import NewsStory

class StoryForm(ModelForm):
    Cuisine_CHOICES = [
        ('French', 'French'),
        ('Italian', 'Italian'),
        ('Modern Australian', 'Modern Australian'),
        ('Indonesian', 'Indonesian'),
        ('Chinese', 'Chinese'),
        ('Japanese', 'Japanese'),
        ('Thai', 'Thai'),
        ('American', 'American'),
        ('Middle Eastern', 'Middle Eastern'),
        ('Indian', 'Indian'),
        ('Moroccan', 'Moroccan'),
        ('Other', 'Other'),
    ]
    
    image_upload = forms.URLField(required=False, help_text='If image path is left blank, a randomly generated image will appear in your article',
    widget=forms.TextInput(attrs={'class': "form_entry"}))
    
    CHOICES = [('1','Awful'),('2','Average'),('3','Okay'),('4','Good'),('5','Fantastic')]
    Food_rating=forms.CharField(label='Overall Experience Rating', widget=forms.RadioSelect(choices=CHOICES))

    pub_date = SplitDateTimeField(
		# use split date time field to allow the user to input both date and time
        widget=SplitDateTimeWidget(
			# we use the split date time widget to specify how the html gets built
            date_attrs={'type': 'date', 'class':'form_entry'},
			# type date tells django to use the HTML5 date input
            time_attrs={'type': 'time','class':'form_entry'},
			# type time tells django to use the HTML5 time input
        )
    )

    class Meta:
        model = NewsStory
        fields = ['title','Restaurant', 'pub_date','image_upload','content','cuisine_type']
        widgets = {
            "content": forms.Textarea(
                attrs={'placeholder': 'We cannot wait to hear where you have eaten and what it was like!','class':'form_entry' },
                )
                ,

            "title": forms.TextInput(
                attrs={
                'class':'form_entry'}
                )
                ,
            "Restaurant": forms.TextInput(
                attrs={
                'class':'form_entry'}
            )    
        }


class StoryFormChangeForm(ModelForm):
    image_upload = forms.URLField(required=False, help_text='If image path is left blank, a randomly generated image will appear in your article',
    widget=forms.TextInput(attrs={'class': "form_entry"}))
    CHOICES = [('1','Awful'),('2','Average'),('3','Okay'),('4','Good'),('5','Fantastic')]
    Food_rating=forms.CharField(label='Overall Experience Rating', widget=forms.RadioSelect(choices=CHOICES))
    pub_date = SplitDateTimeField(
            # use split date time field to allow the user to input both date and time
            widget=SplitDateTimeWidget(
                # we use the split date time widget to specify how the html gets built
                date_attrs={'type': 'date', 'class':'form_entry'},
                # type date tells django to use the HTML5 date input
                time_attrs={'type': 'time','class':'form_entry'},
                # type time tells django to use the HTML5 time input
            )
        )


    class Meta:
        model = NewsStory
        fields = ['title','Restaurant', 'pub_date','image_upload','content','cuisine_type']
        widgets = {
            "content": forms.Textarea(
                attrs={'placeholder': 'We cannot wait to hear where you have eaten and what it was like!','class':'form_entry' },
                )
                ,

            "title": forms.TextInput(
                attrs={
                'class':'form_entry'}
                )
                ,
            "Restaurant": forms.TextInput(
                attrs={
                'class':'form_entry'}
            )    
        }    
        


class UserDeleteForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = []   #Form has only submit button.  Empty "fields" list still necessary, though.

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy, reverse
from .models import NewsStory
from .forms import StoryForm,StoryFormChangeForm,UserDeleteForm
from django.contrib.auth import get_user_model
from users.models import CustomUser, Cuisine_CHOICES
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
User = CustomUser

def LikeView(request, pk):
    newsstory = get_object_or_404(NewsStory,pk=pk)
    newsstory.likes.add(request.user)
    return HttpResponseRedirect(reverse('news:story',args=[str(pk)]))


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.all().order_by('-pub_date')
        context['categories'] = NewsStory.cuisine_type.field.choices
        return context

class ALLIndexView(generic.ListView):
    template_name = 'news/category_page.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_stories'] = NewsStory.objects.all().order_by('-pub_date')
        context['categories'] = NewsStory.cuisine_type.field.choices
        return context

class CategoryFilterView(generic.ListView):
    template_name = 'news/category_page.html'
    context_object_name = 'all_stories'
    slug_field = "cuisine_type"
    slug_url_kwarg = "cuisine_type"

    def get_queryset(self):
        '''Return all news stories.'''
        qs = NewsStory.objects.all()
        q = self.request.GET.get("cuisine_type")
        if q:
            qs =qs.filter(cuisine_type = q)
        return qs

        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['form'] = StoryForm
            context['categories'] = Cuisine_CHOICES
            return context




class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            stuff = get_object_or_404(NewsStory, id=self.kwargs['pk'])
            total_likes = stuff.total_likes()
            context['total_likes'] = total_likes
            context['categories'] = NewsStory.cuisine_type.field.choices
            return context

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = StoryForm.Cuisine_CHOICES
        return context
 


class EditStoryView(generic.edit.UpdateView):
    model = NewsStory
    form_class =  StoryFormChangeForm
    context_object_name = 'storyForm'
    template_name = 'news/editStory.html'
    success_url = reverse_lazy('news:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = NewsStory.cuisine_type.field.choices
        return context



class OneAuthorView(generic.DetailView):
    model = User
    template_name = 'news/one_author.html'
    slug_field = "username"
    slug_url_kwarg = "username"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = User.Cuisine_CHOICES
        return context    

class DeleteStoryView(generic.edit.DeleteView):
    model = NewsStory
    form_class =  UserDeleteForm
    context_object_name = 'storyForm'
    template_name = 'news/deleteStory.html'
    success_url = reverse_lazy('news:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = NewsStory.cuisine_type.field.choices
        return context

she_codes_news/news/templates/news/category_page.html
<!-- extend points it to where it is being inserted -->

{% extends "base.html" %} 
{% load static %}

{% block stylesheets %}
<link rel ='stylesheet' type = "text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    <div id="title-sen">
    {% if user.is_authenticated %}
    <a href="{% url 'news:newsStory' %}">Been to a great {{request.GET.cuisine_type}} restaurant? Write a new restaurant review and let us know about it here!</a>
    {% else %}
        <a href="{% url 'login' %}">Been to a great {{request.GET.cuisine_type}} restaurant? Remember You must be logged in to write a restaurant review</a>
    {% endif %}
    </div>
    <h2>All {{request.GET.cuisine_type}} Reviews</h2>

    <div id="all-stories">
        {% if all_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No reviews have been posted for {{request.GET.cuisine_type}} restaurants yet. Time to get eating and report back to us at She Codes Eats.</p>
        {% endif %}
    </div>
{% endblock %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel ='stylesheet' type = "text/css" href="{% static 'news/styles.css' %}">
{% endblock %}
{% block content %}

{% if user.is_authenticated %}
    <div id = "form-container">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input class = "submitbutton" type="submit" value="submit">
        </form>
    </div>
{% else %}
    <p>Please log in or create an account to create a news story</p>
    <a href="{% url 'login' %}">LOGIN</a>
    <a href="{% url 'users:createAccount' %}">CREATE ACCOUNT</a>


    
{% endif %}

{% endblock %}

she_codes_news/news/templates/news/deleteStory.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel ='stylesheet' type = "text/css" href="{% static 'news/styles.css' %}">
{% endblock %}
{% block content %}


{% if user.is_authenticated and user == storyForm.author %}
    <div id = "form-container">
        <form method="POST">
            {% csrf_token %}
                <h2>Delete Review: {{storyForm.title}}</h2>
                    <p>Are you sure you want to delete your review "{{storyForm.title}}" ?  This will permanently delete the review for restaurant: {{storyForm.Restaurant}} which was published on {{storyForm.pub_date}}</p>
                    {{ form.as_p }}
            <div class="form-group">
                <button class = "submitbutton"  type="submit">Delete Story</button>
            </div>
        </form>
    </div>
{% else %}
    <p>You are not the author of this review.</p>
    <a href="{% url 'news:index' %}">Return to homepage</a >


    
{% endif %}

{% endblock %}

she_codes_news/news/templates/news/editStory.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel ='stylesheet' type = "text/css" href="{% static 'news/styles.css' %}">
{% endblock %}
{% block content %}


{% if user.is_authenticated and user == storyForm.author %}
    <div id = "form-container">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input class = "submitbutton" type="submit" value="Update Story details">
        </form>
    </div>
{% else %}
    <p>You are not the author of this review.</p>
    <a href="{% url 'news:index' %}">Return to homepage</a >


    
{% endif %}

{% endblock %}

she_codes_news/news/templates/news/index.html
<!-- extend points it to where it is being inserted -->

{% extends "base.html" %} 
{% load static %}

{% block stylesheets %}
<link rel ='stylesheet' type = "text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    <div id="welcomesection">
        <p>Hello! Welcome to She {Codes} Eats! </p>
        <p>A place for Perth locals to share their experiences dining out across Western Australia. </p>
        <p>Please share your favourite restaurant dishes, experiences and reccomendations with fellow She {Codes} foodies.</p>
    </div>

    <h2>Latest Reviews</h2>
    <div id="latest-stories">

        {% if latest_stories %}
            {% for story in latest_stories %}
            <!-- looks for template name and sends it story -->
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
{% endblock %}

she_codes_news/news/templates/news/one_author.html
{% extends "base.html" %} 
{% load static %}
{% block stylesheets %}
<link rel ='stylesheet' type = "text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    <div id="user-profile">
        <h2>She Codes Eats User:   {{object}}  </h2>
        <p>Location: {{object.location}}</p>
        <p>Favourite Cuisine: {{object.favourite_cuisine}}</p>
        <p>A bit about {{object}}: {{object.bio}}</p>
        <p>Number of Reviews to date: {{object.stories.all|length}} </p>
        <h2> All reviews written by {{object}}: </h2>

    </div>


    <div id="all-stories">
        {% if object.stories.all %}
            {% for story in object.stories.all %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>{{object}} has not submitted any reviews yet!</p>
        {% endif %}
    </div>
    
{% endblock %} 

she_codes_news/news/templates/news/stories_full.html
<!-- extend points it to where it is being inserted -->

{% extends "base.html" %} 
{% load static %}

{% block stylesheets %}
<link rel ='stylesheet' type = "text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

    {% if user.is_authenticated %}
    <a href="{% url 'news:newsStory' %}">Hi {{user.username}}! Write a new restaurant review!</a>
    {% else %}
        <a href="{% url 'login' %}">You must be logged in to write a restaurant review</a>
    {% endif %}

    <h2>All Reviews</h2>

    <div id="all-stories">
        {% if all_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %} 
{% load static %}

{% block stylesheets %}
<link rel ='stylesheet' type = "text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<div id="story-wrapper">
<div id="story-heading"> 
    <h2>{{ story.title }}</h2>
</div>

    <div id="story-content">
        {% if story.image_upload|length > 0 %}
        <img src="{{ story.image_upload }}">
            {% else %}
        <img src="https://picsum.photos/600">
        {% endif %}
        <h2>Restaurant: {{story.Restaurant}}</h2>
        <h2>Rating: {{story.Food_rating}} / 5</h2>
        <h2 class = "{{story.cuisine_type}}">{{story.cuisine_type}}</h2>

        {{ story.content|linebreaks }}
        <p>{{ story.pub_date }}</p>
        {% if user.is_authenticated and user == story.author %}
            <a class = "navbar" href="{% url 'news:editStory' story.pk %}">Edit Story</a>
            <a class = "navbar" href="{% url 'news:deleteStory' story.pk %}">Delete Story</a>
        {% endif %}

    </div>
</div>



<div id = "edit-story-test">
    {% if user.is_authenticated %}
    <p></p>
    <p>Was this review helpful? Give it a like!</p>

    <form action="{% url 'news:like-post' story.pk %}" method="POST">
        {% csrf_token %}
        <button class = "submitbutton" type="submit",name="post_id",value="{{story.id}}">Like - {{story.total_likes}}</button>
    </form>
    {% endif %}    
    <p>Do you see what other reviews this author has contributed?</p>
    <a class = "navbar" href="{% url 'news:one_author' story.author%}">Profile: {{ story.author }}</a>

</div>



{% endblock %}

she_codes_news/news/templates/news/storyCard.html
{% load static %}

<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if story.image_upload|length > 0 %}
        <img src="{{ story.image_upload }}">

            {% else %}
        <img src="https://picsum.photos/600">
        {% endif %}


        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4 id = "uppercase-storycard">{{story.author}}</h4> 
            <h4 id = "uppercase-storycard" class = "{{story.cuisine_type}}" >{{ story.cuisine_type}}</h4>
            <h4 id = "uppercase-storycard">{{story.total_likes}} Likes</h4> 


        </div>
    </a>
</div>